### ISSUE TITLE
User can create a post #1

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/Art-Alliance#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a post

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can input what they want in their post into the "Post" textbox. Below the "Post" textbox, users can decide if they want to include a date, price, time, and location by selecting the checkbox associated with each parameter and include their value in each textbox.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/147501872-62dc2cfb-9839-4c4a-b018-4e8504dda7f2.png)

![image](https://user-images.githubusercontent.com/90541276/147501854-c6c3d89a-4e73-46b3-8028-9333e0638e74.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Create database.
- [x] Add initial tables: users, posts, and comments

### ☁️ Server

- [x] Create an endpoint POST /api/posts to save a new post

### ⚡ Client

- [x] Create a component to create post page using React jsx with a submit button 
- [x] Style using CSS

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
