### ISSUE TITLE
User can delete comment #10

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/Art-Alliance#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete comment

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the dropdown icon is clicked on a comment, a delete option will appear. Once clicked, a delete modal will be displayed asking the user if they wish to CANCEL or DELETE. If the user clicks CANCEL, the modal will disappear. If the user clicks DELETE, the comment will be removed from the page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/151640278-19d8a004-c3f9-4969-ad76-791abf024779.png)
![image](https://user-images.githubusercontent.com/90541276/151640502-acfb54ed-da4b-4248-88bb-3c40a1848bf0.png)
![image](https://user-images.githubusercontent.com/90541276/151640518-e91341cb-7988-4259-8392-3be2a727d90f.png)
![image](https://user-images.githubusercontent.com/90541276/151640525-4e766c27-e4aa-428e-bd57-431f1519120c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include a DELETE comment endpoint using commentID
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create method to delete comment using commentId when DELETE button is clicked

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
