### ISSUE TITLE
User can view posts #2

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/Art-Alliance#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view posts

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user hits submit on the post page, the page will revert to it's normal home page state and display every post made in the database.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/147505574-76672f1d-35ed-46ef-8917-3b68fb5aa68e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create endpoint GET /api/posts to get all available posts

### ⚡ Client

- [x] Create a component to build home page in React jsx

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
