### ISSUE TITLE
User can edit post #3

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/Art-Alliance#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit post

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the 3 horizontal dots on their post. Once clicked, a dropdown menu will appear. User can then click on Edit and a Edit Modal will appear on the page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/147998727-1fb61a27-c584-4f67-b3c4-f5ac76ea8717.png)
![image](https://user-images.githubusercontent.com/90541276/147998754-7779cf16-63fd-48dc-b887-ccb549c7d5c8.png)
![image](https://user-images.githubusercontent.com/90541276/147998813-3073ab0a-d5e3-442d-befd-288b0e9fa10c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Create endpoint PUT /api/posts/id to retrieve individual post
- [x] Update `data.sql` to return one post using matching postId and userId

### ⚡ Client

- [x]  Update Home component to include drop down menu for options button. Include Edit and Delete options
- [x]  Create a component to build edit modal in React jsx
- [x]  Add click event listener on Edit Button onClick to display edit modal
- [x]  Retrieve form info from post that was clicked and display in edit modal
- [x]  Update post page to include edit post 

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
