### ISSUE TITLE
User can delete post #4

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/Art-Alliance#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete post

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Under the dropdown menu, users can click on Delete. Once clicked, a modal will appear asking for confirmation from the user. Users can then click Cancel to cancel the request and close the modal or Delete to delete the post.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/148431121-5b666500-993b-495a-a945-21eba6ae73b2.png)
![image](https://user-images.githubusercontent.com/90541276/148431432-92e82c23-83a2-470a-b629-61caeaf640dd.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to create delete endpoint to remove post from database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a new jsx page called "delete" and create a confirmation modal
- [x] Add click event listener on "delete" button in dropdown.jsx to open the confirmation modal
- [x] Add click event listener on "Cancel" button in the modal to close modal
- [x] Add click event listener on "Delete" button in confirmation modal to delete entry from the list

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
