### ISSUE TITLE
User can save posts #5

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/Art-Alliance#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save posts

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the users views another user's post, a star will appear on the right side of the post where the drop down icon is supposed to be. If clicked, the star will turn yellow signifying that it has been added to a saved collection. Users can then click on the star again to revert the color back to normal and remove it from the saved collection.
 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/148471836-65e3371c-8c97-4a18-a19a-d1f18e393589.png)
![image](https://user-images.githubusercontent.com/90541276/148471856-e8aa42c1-b066-4e65-99d5-204c2d8aadb1.png)
![image](https://user-images.githubusercontent.com/90541276/148471870-0c36bdb3-b721-402a-aaea-319ae13473d8.png)
![image](https://user-images.githubusercontent.com/90541276/148471897-849adf88-1920-4978-a3a1-15a915342a0e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to include extra dummy userId's and create posts using these new Id's
- [x] Create a saved table using schema

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a star icon in post.jsx
- [x] If users views their post, display a dropdown icon. If users views another user's post, display a star icon.
- [x] If user clicks on a the bookmark icon, make a get request and add to saved table.

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
