### ISSUE TITLE
User can view saved posts #6

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/Art-Alliance#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view saved posts

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the Saved Icon at the top right of the navigation bar. Once clicked, a saved page will display with all the bookmarked posts.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/148639155-4d202037-29cb-48a2-ae54-ba7e15c8c0d7.png)
![image](https://user-images.githubusercontent.com/90541276/148639733-5de8d768-11d7-4ad0-8afe-89a83e59f921.png)

![image](https://user-images.githubusercontent.com/90541276/148639177-4e04c58c-f2a1-409d-a1bf-95b063184698.png)
![image](https://user-images.githubusercontent.com/90541276/148690905-51a46351-391a-4d06-b347-cd3bea3f1069.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create a app.get api/favorites/:userId endpoint.
- [x] Create sql and use "join" to include all the contents associated with the saved post
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a saved.jsx page component to display a new saved page. Use map().
- [x] Add click functionality to navigation bar for both Home and Saved icons so that user can switch between pages.
- [x] Create a savedPost.jsx component to handle a single saved post as a li and display all the saved posts on the page.
- [x] Create a removeSaved.jsx component and display a remove confirmation modal
- [x] Add click listener to bookmark for each post. If user clicks it, the post will be removed from the saved page.

### 🧑‍⚕️ Clean Up

- [x] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
