### ISSUE TITLE
User can view comments on a post #7

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/Art-Alliance#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can views comment on a post

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On every post, there will be a comment button at the bottom. Once clicked, the user will be taken to a Comments page where the post will be displayed with all the comments associated with the post below it. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/150197386-0cf0c3e2-4945-426d-9a7f-5d67091ae5ae.png)
![image](https://user-images.githubusercontent.com/90541276/150197461-4790fbab-ae5f-4562-8ce0-b6f0e27ce099.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to include test comments

### ☁️ Server

- [x] Create endpoint to GET comments for a single post
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a comments component to display post and the comments

### 🧑‍⚕️ Clean Up

- [x] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
