### ISSUE TITLE
User can add comment #8

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/Art-Alliance#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can comment on post

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the comments page, user can click on the add comment section and open up a new text box. User can then type down their comment and post it onto the page. User can also cancel to exit the text box.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/150612980-2a07edf8-3f75-4c91-8534-37ae2fbfcb34.png)
![image](https://user-images.githubusercontent.com/90541276/150612993-590f392b-3311-4814-9b71-70509c6734df.png)
![image](https://user-images.githubusercontent.com/90541276/150613518-0b8bb097-ff74-41cb-9435-cb8c355f330d.png)

![image](https://user-images.githubusercontent.com/90541276/150613027-1893ccce-6f02-4b66-9314-0a185e21acdd.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to add a comment into the comments table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update comment component to display textbox when "Add a public Comment" button is clicked.
- [x] Include a cancel and post button.
- [x] If cancel is clicked, the text box will be closed and the value in the textbox will be reset.
- [x] If post is clicked, the page will be updated with the new comment that was added.

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
