### ISSUE TITLE
User can edit comment #9

### ISSUE THREAD

**Issue by John-Baik** [John-Baik/Art-Alliance#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit comment

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the dropdown icon on a comment to bring up the "Edit" and "Delete" buttons. If "Edit" is clicked, then the comment will be replaced by a text box with the comment's value. User can then change the comment and click "Cancel" or "Post".

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90541276/150703674-dc7484d5-c8ce-4170-a39e-0b81b854469f.png)
![image](https://user-images.githubusercontent.com/90541276/150703689-71921199-a280-401b-b54a-45cce41e114c.png)
![image](https://user-images.githubusercontent.com/90541276/150703706-7117e91e-b51f-4bf2-8352-88adb827606c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to update comment using commentId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] If userId that is logged in matches the comment's userId, update singleComment.jsx display a dropdown icon. If not, then display nothing.
- [x] If dropdown icon is clicked, display dropdown options using dropdown.jsx
- [x] When Edit button is clicked, replace comment with a textbox with the original comment's value and a Cancel and Post Button
- [x] User can then click on Post to update the comment 

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
